### ISSUE TITLE
widget是干啥用的？该怎么用？

### ISSUE THREAD

**Issue by lujun9972** [aborn/v2ex-mode#1]

**Comment by aborn** [comment]
参考：
https://www.gnu.org/software/emacs/manual/html_mono/widget.html
https://www.emacswiki.org/emacs/widget-demo.el

**Comment by lujun9972** [comment]
这个…直接看manual太繁琐了，能大至讲讲吗？

**Comment by aborn** [comment]
额。。。我也还刚开始学，照葫芦画瓢。 :)
