### ISSUE TITLE
推荐用request代替url

### ISSUE THREAD

**Issue by lujun9972** [aborn/v2ex-mode#3]
因为url不太稳定而且据说bug比较多，而request在curl存在情况下会优先用curl
http://nullprogram.com/blog/2016/06/16/

**Comment by aborn** [comment]
加你为collaborator，一起开发吧，反正我也是写着好玩。之所以没有request，不想有太多依赖。

**Comment by lujun9972** [comment]
好的，不过我最近在学python，也很少写elisp了:)
