### ISSUE TITLE
v2ex-mode继承自 Tabulated List mode

是不是更好点

### ISSUE THREAD

**Issue by lujun9972** [aborn/v2ex-mode#4]

**Comment by aborn** [comment]
按照 purcell 的建议，https://github.com/melpa/melpa/pull/4003 ，应该继承自special-mode比较好。想不到，purcell好认真，还会帮忙review代码。

**Comment by lujun9972** [comment]
tabulated list mode就是继承自special mode的

**Comment by xuchunyang** [comment]
我觉得会，看起来应该会更整齐些。
