### ISSUE TITLE
无法获取主题列表

### ISSUE THREAD

**Issue by ywmmmw** [aborn/v2ex-mode#6]
> open v2ex.com
> Contacting host: www.v2ex.com:443
> Opening TLS connection to `www.v2ex.com'...
> Opening TLS connection with`gnutls-cli --insecure -p 443 www.v2ex.com'...failed
> Opening TLS connection with `gnutls-cli --insecure -p 443 www.v2ex.com --protocols ssl3'...failed
> Opening TLS connection with`openssl s_client -connect www.v2ex.com:443 -no_ssl2 -ign_eof'...done
> Opening TLS connection to `www.v2ex.com'...done
> v2ex: Symbol's value as variable is void: id

直接从Message里获取的日志
安装自popkit elpa
版本20160624.2347
emacs版本GUN Emacs 24.5.1

**Comment by aborn** [comment]
在popkit elpa里的最新版本，我已经把无用的变量id去掉了，你再试试看。 @fuxinlei

**Comment by ywmmmw** [comment]
👍 已经可以正常使用，谢谢 😄
